apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-slow-single-replica
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  diskSelector: "hdd"
  dataLocality: "strict-local"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer