apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-fast-single-replica
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  diskSelector: "ssd"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer