apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cnpg-ingress
  namespace: cnpg-pods
spec:
  ingressClassName: nginx
  rules:
    - host: cnpg.home.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: cnpg-rw-lb
                port:
                  number: 5432