apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: portfolio-ingress
  namespace: portfolio
  labels:
    app.kubernetes.io/name: portfolio-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: fayadchowdhury.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-frontend-loadbalancer
                port:
                  number: 80

          - path: /api
            pathType: Prefix
            backend:
              service:
                name: portfolio-backend-loadbalancer
                port:
                  number: 80