apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- secrets.yaml
- frontend-deploy.yaml
- frontend-loadbalancer.yaml
- backend-deploy.yaml
- backend-loadbalancer.yaml
- ingress.yaml