apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-slack-webhook
    namespace: monitoring
type: Opaque
stringData:
    webhook-url: ENC[AES256_GCM,data:60cElO93vhkkHR3QATQY2jIldH2lE9J7f+59Yfj5Fenq6aRceQaPMbXr8kO8ytfarsNA1deYUIjrgo+Vp+rhDCexrb+hPSd7OPnPRV1L77WQ,iv:yWLrPfSDreyBDYE6oQsoOR370+ahKONrHlMFjiP/FJ8=,tag:gaXwoESj/ZRQzHQ9tgJ+jw==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZmw2WXdBZEhmVGhIMW1G
            NjdZZXpqcTVoSjNlOGxFZHRuY2JGdWdBR1RvCmd6ZXN1cFpRMjRDUHNnS2RXWFB6
            MURNUGNUZzJOUFN0bkFyZzYzdkMvVkUKLS0tIFBaSjl0bVBCV1dza0tySDg0aVYv
            YjNHcnRtc2dzSzB0MVpyMDZMMkZvS3cKauuVWSmlN0m/mWarbv1uX/rnmS5swSXm
            WRjAg7slpJ3CXctOBMRtPDaxfY5tCaXEDBeXlipKRG2+guNYL9yh/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T18:41:27Z"
    mac: ENC[AES256_GCM,data:AGS7LRpTKhcrJ5fk/6RbzOqlRRNSLFuNL0tD7yBFdyrXlKxWuXpCkDK+fP/GZccCh8osIHVU7TXFOzfxDEBZYMQdRpVunUV4IF4Oagr9nWrKD4U4xopJS0abqoyCSyTCPB7+bTfaH9c/7LqHXRd71MfFtzOJYi4U47hOPs3veD4=,iv:k1+cSRtaF6AcAK26gytWLtv4tjxIfL8GUmxlRvygmjc=,tag:objarvKE6NxIFpmks3XgIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
