---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-1
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "ssd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-2
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "ssd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-3
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "ssd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-4
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "ssd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-5
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "ssd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-6
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "hdd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-7
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "hdd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-8
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "hdd"
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: k8s-worker-9
  namespace: longhorn-system
spec:
  allowScheduling: true
  evictionRequested: false
  
  disks:
    disk:
      path: /var/lib/longhorn
      allowScheduling: true
      evictionRequested: false
      tags:
      - "hdd"