apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - cloudflare-api-token-secret.yaml
  - cloudflare-cluster-issuer.yaml
  - self-signed-cluster-issuer.yaml
  - internal-tls-cert.yaml