---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik-repo
      version: ">=28.0.0"
  interval: 1m0s
  install:
    timeout: 30m
    remediation:
      retries: 3
  upgrade:
    timeout: 30m
  values:
    deployment:
      replicas: 1
    providers:
      kubernetesIngress:
        enabled: true
        ingressClass: traefik
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: false
    service:
      type: LoadBalancer
    gateway:
      enabled: true
      name: traefik-gateway
      listeners:
        http-public:
          port: 8000
          protocol: HTTP
          hostname: "fayadchowdhury.com"
          namespacePolicy:
            from: All
        http-public-wildcard:
          port: 8000
          protocol: HTTP
          hostname: "*.fayadchowdhury.com"
          namespacePolicy:
            from: All
        http-internal:
          port: 8000
          protocol: HTTP
          hostname: "*.home.com"
          namespacePolicy:
            from: All
        https-internal:
          port: 8443
          protocol: HTTPS
          hostname: "*.home.com"
          namespacePolicy:
            from: All
          certificateRefs:
            - name: internal-tls-cert
              kind: Secret
          mode: Terminate
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik-dashboard.home.com`)
        entryPoints:
          - web
    logs:
      general:
        level: INFO
