apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - grafana-secret.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - httpsroute.yaml
  - prometheus-rules
  - alertmanager-configs