apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/cloudnative-pg/plugin-barman-cloud/releases/download/v0.11.0/manifest.yaml
- minio-credentials-secret.yaml
- create-barman-bucket.yaml
- barman-object-store.yaml
- scheduled-barman-store-backups.yaml
- namespace.yaml
- pg-cluster.yaml