apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:m1pK51k=,iv:tlDScgjakTw8b855Y/tJcfMwnyzUyhoWRMkfy9grGPY=,tag:gd3pQsTnBILiyJKbkEbvlw==,type:str]
    admin-password: ENC[AES256_GCM,data:enbUVP+wfcNgc+0M,iv:OFcY0k3SkqoeGaUpVA2XmRTIUlrVhKzk0QmvVJiOqFY=,tag:UrKEhtOKWdgBr07RJe4izA==,type:str]
sops:
    age:
        - recipient: age10ksdmv2awqtaawdcykp7xqpk03t0w2dam92jyzqa945cpmk3t46s7z5xmd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmemV3SUNyV0tkTlpLQjEw
            OERaYUhtWEx1S2o5Z3hrRmZVMTJKRzg2aVFzClBsWnBRTTlJd1QrRlJwYURyVDdh
            YjZ5OW1sMVdiZ1plUDhyM3hVSFVDeGMKLS0tIEo5QklrVFhDNWx6N1ZScDlnWVpP
            cGNqQ2w3dlRpVUQyblFDZG9KRWJORlkKacrbOvZVBsIjwZ+jDp2zkBgs/mtd+7wC
            nkR9igptaC13yEEmd4DHf+I6HDrmNYK24xsJKdCIX/IjVBnajWtsLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-23T18:36:08Z"
    mac: ENC[AES256_GCM,data:857BZ2mnVybGoP1tbKXlv0afUwnDt4pAzbA4vJpK3MRaaMvI4TlUjLbCQqBtfEarCpsVkzOkxYgU5SRlKYpIPkDwTc/Antfks4t9meKw/YHypYycR8nxshcuFPX/EFTNk+LiMphERVYQEO1c/vbG2e+OpP8xRZAZyeUfpNLZgRo=,iv:uMPTcoDRGcvJHTR3D1saEPdcejG+a4jxRiLpjkbWEDE=,tag:WPI1XYIgKyjEjrNxD1pfRA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
