apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- crds.yaml
- core.yaml
- config.yaml
- gateway.yaml
- platform.yaml
- apps.yaml
- notifications.yaml