apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: config-github-status
  namespace: flux-system
spec:
  providerRef:
    name: github-status
  eventSources:
    - kind: Kustomization
      name: config
      namespace: flux-system